/*
 * keywords.c - Table des mots-cles GFA Basic 3.5
 * ===============================================
 * Table exhaustive des ~280 mots-cles du GFA Basic 3.5
 * avec leur token associe. Recherche dichotomique pour
 * la performance (table triee par ordre alphabetique).
 */

#include "keywords.h"
#include <string.h>
#include <ctype.h>

/*
 * Table triee alphabetiquement pour recherche dichotomique.
 */
const gfa_keyword_entry gfa_keywords[] = {
    {"ABS",                TOK_ABS},
    {"ABSOLUTE",           TOK_ABSOLUTE},
    {"ACHAR",              TOK_ACHAR},
    {"ACLIP",              TOK_ACLIP},
    {"ACOS",               TOK_ACOS},
    {"ADD",                TOK_ADD},
    {"ADDRIN",             TOK_CONTRL},
    {"ADDROUT",            TOK_CONTRL},
    {"AFTER",              TOK_AFTER},
    {"ALERT",              TOK_ALERT},
    {"ALINE",              TOK_ALINE},
    {"AND",                TOK_AND_OP},
    {"APOLY",              TOK_APOLY},
    {"APPL_EXIT",          TOK_APPL_EXIT},
    {"APPL_FIND",          TOK_APPL_FIND},
    {"APPL_INIT",          TOK_APPL_INIT},
    {"APPL_READ",          TOK_APPL_READ},
    {"APPL_TPLAY",         TOK_APPL_TPLAY},
    {"APPL_TRECORD",       TOK_APPL_TRECORD},
    {"APPL_WRITE",         TOK_APPL_WRITE},
    {"ARECT",              TOK_ARECT},
    {"ARRAYFILL",          TOK_ARRAYFILL},
    {"ARRPTR",             TOK_ARRPTR},
    {"ASC",                TOK_ASC},
    {"ASIN",               TOK_ASIN},
    {"AT",                 TOK_PRINT_AT},
    {"ATAN",               TOK_ATN},
    {"ATEXT",              TOK_ATEXT},
    {"ATN",                TOK_ATN},
    {"AUTO",               TOK_AUTO},
    {"BASEPAGE",           TOK_BASEPAGE},
    {"BCHG",               TOK_BCHG},
    {"BCLR",               TOK_BCLR},
    {"BEEP",               TOK_BEEP},
    {"BGET",               TOK_BGET},
    {"BIN",                TOK_BIN_TOK},
    {"BIN$",               TOK_BIN_TOK},
    {"BIOS",               TOK_BIOS},
    {"BITBLT",             TOK_BITBLT},
    {"BLOAD",              TOK_BLOAD},
    {"BMOVE",              TOK_BMOVE},
    {"BOUNDARY",           TOK_BOUNDARY},
    {"BOX",                TOK_BOX},
    {"BPUT",               TOK_BPUT},
    {"BREAK",              TOK_ON_BREAK},
    {"BSAVE",              TOK_BSAVE},
    {"BSET",               TOK_BSET},
    {"BTST",               TOK_BTST},
    {"BYTE",               TOK_BYTE_TOK},
    {"C:",                 TOK_C},
    {"CALL",               TOK_CALL},
    {"CARD",               TOK_CARD},
    {"CASE",               TOK_CASE},
    {"CFLOAT",             TOK_CFLOAT},
    {"CHAIN",              TOK_CHAIN},
    {"CHDIR",              TOK_CHDIR},
    {"CHDRIVE",            TOK_CHDRIVE},
    {"CHR",                TOK_CHR_TOK},
    {"CHR$",               TOK_CHR_TOK},
    {"CINT",               TOK_CINT},
    {"CIRCLE",             TOK_CIRCLE_TOK},
    {"CLEAR",              TOK_CLEAR},
    {"CLEARW",             TOK_CLEARW},
    {"CLIP",               TOK_CLIP},
    {"CLOSE",              TOK_CLOSE},
    {"CLOSEW",             TOK_CLOSEW},
    {"CLR",                TOK_CLR},
    {"CLS",                TOK_CLS},
    {"COLOR",              TOK_COLOR},
    {"COMBIN",             TOK_COMBIN},
    {"CONIN",              TOK_CONIN},
    {"CONOUT",             TOK_CONOUT},
    {"CONOUTI",            TOK_CONOUTI},
    {"CONT",               TOK_CONT},
    {"CONTRL",             TOK_CONTRL},
    {"COS",                TOK_COS},
    {"COSH",               TOK_COSH},
    {"COSQ",               TOK_COSQ},
    {"CRSCOL",             TOK_CRSCOL},
    {"CRSLIN",             TOK_CRSLIN},
    {"CURVE",              TOK_CURVE},
    {"CVD",                TOK_CVD_TOK},
    {"CVD$",               TOK_CVD_TOK},
    {"CVF",                TOK_CVF_TOK},
    {"CVF$",               TOK_CVF_TOK},
    {"CVI",                TOK_CVI_TOK},
    {"CVI$",               TOK_CVI_TOK},
    {"CVL",                TOK_CVL_TOK},
    {"CVL$",               TOK_CVL_TOK},
    {"CVS",                TOK_CVS_TOK},
    {"CVS$",               TOK_CVS_TOK},
    {"DATA",               TOK_DATA},
    {"DATE",               TOK_DATE_TOK},
    {"DATE$",              TOK_DATE_TOK},
    {"DEBUG",              TOK_DEBUG},
    {"DEC",                TOK_DEC},
    {"DEFAULT",            TOK_DEFAULT},
    {"DEFBIT",             TOK_DEFBIT},
    {"DEFBYT",             TOK_DEFBYT},
    {"DEFDBL",             TOK_DEFDBL},
    {"DEFFILL",            TOK_DEFFILL},
    {"DEFFLT",             TOK_DEFFLT},
    {"DEFFN",              TOK_DEFFN},
    {"DEFLINE",            TOK_DEFLINE},
    {"DEFLIST",            TOK_DEFLIST},
    {"DEFMARK",            TOK_DEFMARK},
    {"DEFMOUSE",           TOK_DEFMOUSE},
    {"DEFNUM",             TOK_DEFNUM},
    {"DEFSTR",             TOK_DEFSTR},
    {"DEFTEXT",            TOK_DEFTEXT},
    {"DEFWRD",             TOK_DEFWRD},
    {"DEG",                TOK_DEG},
    {"DELAY",              TOK_DELAY},
    {"DELETE",             TOK_DELETE},
    {"DFREE",              TOK_DFREE},
    {"DIM",                TOK_DIM},
    {"DIM?",               TOK_DIM_QUESTION},
    {"DIR",                TOK_DIR_TOK},
    {"DIR$",               TOK_DIR_TOK2},
    {"DIV",                TOK_DIV_OP},
    {"DMACONTROL",         TOK_DMACONTROL},
    {"DMASOUND",           TOK_DMASOUND},
    {"DO",                 TOK_DO},
    {"DOUBLE",             TOK_DOUBLE_TOK},
    {"DOWNTO",             TOK_DOWNTO},
    {"DPEEK",              TOK_DPEEK},
    {"DPOKE",              TOK_DPOKE},
    {"DRAW",               TOK_DRAW},
    {"DUMP",               TOK_DUMP},
    {"ELSE",               TOK_ELSE},
    {"END",                TOK_END},
    {"ENDFUNC",            TOK_ENDFUNC},
    {"ENDIF",              TOK_ENDIF},
    {"ENDPROC",            TOK_ENDPROC},
    {"ENDSELECT",          TOK_ENDSELECT},
    {"EOF",                TOK_EOF_TOK},
    {"EQV",                TOK_EQV_OP},
    {"ERASE",              TOK_ERASE},
    {"ERR",                TOK_ERR},
    {"ERR$",               TOK_ERR},
    {"ERROR",              TOK_ERROR},
    {"EVEN",               TOK_EVEN},
    {"EVERY",              TOK_EVERY},
    {"EVNT_BUTTON",        TOK_EVNT_BUTTON},
    {"EVNT_DCLICK",        TOK_EVNT_DCLICK},
    {"EVNT_KEYBD",         TOK_EVNT_KEYBD},
    {"EVNT_MESAG",         TOK_EVNT_MESAG},
    {"EVNT_MOUSE",         TOK_EVNT_MOUSE},
    {"EVNT_MULTI",         TOK_EVNT_MULTI},
    {"EVNT_TIMER",         TOK_EVNT_TIMER},
    {"EXEC",               TOK_EXEC},
    {"EXIST",              TOK_EXIST},
    {"EXIT",               TOK_EXIT_IF},
    {"EXP",                TOK_EXP},
    {"FACT",               TOK_FACT},
    {"FALSE",              TOK_FALSE},
    {"FATAL",              TOK_FATAL},
    {"FGETDTA",            TOK_FGETDTA},
    {"FIELD",              TOK_FIELD},
    {"FILES",              TOK_FILES},
    {"FILESELECT",         TOK_FILESELECT},
    {"FILL",               TOK_FILL},
    {"FIX",                TOK_FIX},
    {"FLOAT",              TOK_DOUBLE_TOK},
    {"FN",                 TOK_FN},
    {"FOR",                TOK_FOR},
    {"FORM_ALERT",         TOK_FORM_ALERT},
    {"FORM_BUTTON",        TOK_FORM_BUTTON},
    {"FORM_CENTER",        TOK_FORM_CENTER},
    {"FORM_DIAL",          TOK_FORM_DIAL},
    {"FORM_DO",            TOK_FORM_DO},
    {"FORM_ERROR",         TOK_FORM_ERROR},
    {"FORM_INPUT",         TOK_FORM_INPUT},
    {"FORM_KEYBD",         TOK_FORM_KEYBD},
    {"FRAC",               TOK_FRAC},
    {"FRE",                TOK_FRE},
    {"FSEL_INPUT",         TOK_FSEL_INPUT},
    {"FSETDTA",            TOK_FSETDTA},
    {"FSFIRST",            TOK_FSFIRST},
    {"FSNEXT",             TOK_FSNEXT},
    {"FUNCTION",           TOK_FUNCTION},
    {"GEMDOS",             TOK_GEMDOS},
    {"GEMSYS",             TOK_GEMSYS},
    {"GET",                TOK_GET},
    {"GETSIZE",            TOK_GETSIZE},
    {"GINTIN",             TOK_GINTIN},
    {"GINTOUT",            TOK_GINTOUT},
    {"GOSUB",              TOK_GOSUB},
    {"GOTO",               TOK_GOTO},
    {"GRAF_DRAGBOX",       TOK_GRAF_DRAGBOX},
    {"GRAPHICS",           TOK_GRAPHICS},
    {"HARDCOPY",           TOK_HARDCOPY},
    {"HEX",                TOK_HEX_TOK},
    {"HEX$",               TOK_HEX_TOK},
    {"HIDEM",              TOK_HIDEM},
    {"HIMEM",              TOK_HIMEM},
    {"HLINE",              TOK_HLINE},
    {"HTAB",               TOK_HTAB},
    {"IF",                 TOK_IF},
    {"IMP",                TOK_IMP_OP},
    {"INC",                TOK_INC},
    {"INFOW",              TOK_INFOW},
    {"INKEY",              TOK_INKEY},
    {"INKEY$",             TOK_INKEY},
    {"INLINE",             TOK_INLINE},
    {"INP?",               TOK_INP},
    {"INPMID",             TOK_INPMID},
    {"INPMID$",            TOK_INPMID},
    {"INPUT",              TOK_INPUT},
    {"INPUT$",             TOK_INPUT_TOK},
    {"INSERT",             TOK_INSERT},
    {"INSTR",              TOK_INSTR},
    {"INT",                TOK_INT},
    {"INTIN",              TOK_INTIN},
    {"INTOUT",             TOK_INTOUT},
    {"KEY",                TOK_KEY},
    {"KEYDEF",             TOK_KEYDEF},
    {"KEYGET",             TOK_KEYGET},
    {"KEYLOOK",            TOK_KEYLOOK},
    {"KEYPAD",             TOK_KEYPAD},
    {"KEYPRESS",           TOK_KEYPRESS},
    {"KEYTEST",            TOK_KEYTEST},
    {"KILL",               TOK_KILL},
    {"LCASE",              TOK_LCASE_TOK},
    {"LCASE$",             TOK_LCASE_TOK},
    {"LEFT",               TOK_LEFT_TOK},
    {"LEFT$",              TOK_LEFT_TOK},
    {"LEN",                TOK_LEN},
    {"LET",                TOK_LET},
    {"LINE",               TOK_LINE_TOK},
    {"LIST",               TOK_LIST},
    {"LLIST",              TOK_LLIST},
    {"LOAD",               TOK_LOAD},
    {"LOC",                TOK_LOC},
    {"LOCAL",              TOK_LOCAL},
    {"LOCATE",             TOK_LOCATE},
    {"LOF",                TOK_LOF},
    {"LOG",                TOK_LOG},
    {"LOG10",              TOK_LOG10},
    {"LONG",               TOK_LONG_TOK},
    {"LOOP",               TOK_LOOP},
    {"LOWER",              TOK_LOWER_TOK},
    {"LOWER$",             TOK_LOWER_TOK},
    {"LPEEK",              TOK_LPEEK},
    {"LPENX",              TOK_LPENX},
    {"LPENY",              TOK_LPENY},
    {"LPOKE",              TOK_LPOKE},
    {"LPOS",               TOK_LPEN_TOK},
    {"LPRINT",             TOK_PRINT},
    {"LSET",               TOK_LSET},
    {"MALLOC",             TOK_MALLOC},
    {"MAT",                TOK_MAT},
    {"MAX",                TOK_MAX},
    {"MENU",               TOK_MENU},
    {"MENU_BAR",           TOK_MENU_BAR},
    {"MENU_ICHECK",        TOK_MENU_ICHECK},
    {"MENU_IENABLE",       TOK_MENU_IENABLE},
    {"MENU_REGISTER",      TOK_MENU_REGISTER},
    {"MENU_TEXT",          TOK_MENU_TEXT},
    {"MENU_TNORMAL",       TOK_MENU_TNORMAL},
    {"MERGE",              TOK_MERGE},
    {"MFREE",              TOK_MFREE},
    {"MID",                TOK_MID_TOK},
    {"MID$",               TOK_MID_TOK},
    {"MIN",                TOK_MIN},
    {"MKD",                TOK_MKD_TOK},
    {"MKD$",               TOK_MKD_TOK},
    {"MKDIR",              TOK_MKDIR},
    {"MKF",                TOK_MKF_TOK},
    {"MKF$",               TOK_MKF_TOK},
    {"MKI",                TOK_MKI_TOK},
    {"MKI$",               TOK_MKI_TOK},
    {"MKL",                TOK_MKL_TOK},
    {"MKL$",               TOK_MKL_TOK},
    {"MKS",                TOK_MKS_TOK},
    {"MKS$",               TOK_MKS_TOK},
    {"MOD",                TOK_MOD_OP},
    {"MODE",               TOK_MODE},
    {"MONITOR",            TOK_MONITOR},
    {"MOUSE",              TOK_MOUSE},
    {"MOUSEK",             TOK_MOUSEK},
    {"MOUSEX",             TOK_MOUSEX},
    {"MOUSEY",             TOK_MOUSEY},
    {"MSHRINK",            TOK_MSHRINK},
    {"MUL",                TOK_MUL_TOK},
    {"MWOUT",              TOK_MW_OUT},
    {"NAME",               TOK_NAME},
    {"NEW",                TOK_NEW},
    {"NEXT",               TOK_NEXT},
    {"NOT",                TOK_NOT_OP},
    {"OBJC_ADD",           TOK_OBJC_ADD},
    {"OBJC_ADDMOVE",       TOK_OBJC_ADDMOVE},
    {"OBJC_CHANGE",        TOK_OBJC_CHANGE},
    {"OBJC_DELETE",        TOK_OBJC_DELETE},
    {"OBJC_DRAW",          TOK_OBJC_DRAW},
    {"OBJC_EDIT",          TOK_OBJC_EDIT},
    {"OBJC_FIND",          TOK_OBJC_FIND},
    {"OBJC_MOVE",          TOK_OBJC_MOVE},
    {"OBJC_OFFSET",        TOK_OBJC_OFFSET},
    {"OBJC_ORDER",         TOK_OBJC_ORDER},
    {"OBJC_PICK",          TOK_OBJC_PICK},
    {"OBJC_STATE",         TOK_OBJC_STATE},
    {"OBJC_TNORMAL",       TOK_OBJC_TNORMAL},
    {"OB_ADR",             TOK_OB_ADR},
    {"OB_FLAGS",           TOK_OB_FLAGS},
    {"OB_H",               TOK_OB_H},
    {"OB_HEAD",            TOK_OB_HEAD},
    {"OB_NEXT",            TOK_OB_NEXT},
    {"OB_SPEC",            TOK_OB_SPEC},
    {"OB_STATE",           TOK_OB_STATE},
    {"OB_TAIL",            TOK_OB_TAIL},
    {"OB_TYPE",            TOK_OB_TYPE},
    {"OB_W",               TOK_OB_W},
    {"OB_X",               TOK_OB_X},
    {"OB_Y",               TOK_OB_Y},
    {"OCT",                TOK_OCT_TOK},
    {"OCT$",               TOK_OCT_TOK},
    {"ODD",                TOK_ODD},
    {"ON",                 TOK_ON},
    {"OPEN",               TOK_OPEN},
    {"OPENW",              TOK_OPENW},
    {"OPTION",             TOK_OPTION_BASE},
    {"OR",                 TOK_OR_OP},
    {"OUT",                TOK_OUT},
    {"PADT",               TOK_PADT},
    {"PADX",               TOK_PADX},
    {"PADY",               TOK_PADY},
    {"PAUSE",              TOK_PAUSE},
    {"PBOX",               TOK_PBOX},
    {"PCIRCLE",            TOK_PCIRCLE},
    {"PEEK",               TOK_PEEK},
    {"PELLIPSE",           TOK_PELLIPSE},
    {"PI",                 TOK_PI_TOK},
    {"PLOT",               TOK_PLOT},
    {"POINT",              TOK_POINT},
    {"POKE",               TOK_POKE},
    {"POLYFILL",           TOK_POLYFILL},
    {"POLYLINE",           TOK_POLYLINE},
    {"POLYMARK",           TOK_POLYMARK},
    {"POS",                TOK_POS},
    {"PRBOX",              TOK_PRBOX},
    {"PRED",               TOK_PRED},
    {"PRINT",              TOK_PRINT},
    {"PROC",               TOK_PROC},
    {"PROCEDURE",          TOK_PROCEDURE},
    {"PSAVE",              TOK_PSAVE},
    {"PTSIN",              TOK_PTSIN},
    {"PTSOUT",             TOK_PTSOUT},
    {"PTST",               TOK_PTST},
    {"PUT",                TOK_PUT},
    {"QSORT",              TOK_QSORT},
    {"QUIT",               TOK_QUIT},
    {"RAD",                TOK_RAD},
    {"RAND",               TOK_RANDOM},
    {"RANDOM",             TOK_RANDOM},
    {"RANDOMIZE",          TOK_RANDOMIZE},
    {"RBOX",               TOK_RBOX},
    {"RCALL",              TOK_RCALL},
    {"RC_COPY",            TOK_RC_COPY},
    {"RC_INTERSECT",       TOK_RC_INTERSECT},
    {"READ",               TOK_READ},
    {"RECALL",             TOK_RECALL},
    {"RECORD",             TOK_RECORD},
    {"RELSEEK",            TOK_RELSEEK},
    {"REM",                TOK_REM},
    {"RENAME",             TOK_NAME},
    {"RENUM",              TOK_RENUM},
    {"REPEAT",             TOK_REPEAT},
    {"RESERVE",            TOK_RESERVE},
    {"RESTORE",            TOK_RESTORE},
    {"RESUME",             TOK_RESUME},
    {"RETURN",             TOK_RETURN},
    {"RIGHT",              TOK_RIGHT_TOK},
    {"RIGHT$",             TOK_RIGHT_TOK},
    {"RINSTR",             TOK_RINSTR},
    {"RMDIR",              TOK_RMDIR},
    {"RND",                TOK_RND},
    {"ROL",                TOK_ROL},
    {"ROR",                TOK_ROR},
    {"ROUND",              TOK_ROUND},
    {"RSET",               TOK_RSET},
    {"RSRC_FREE",          TOK_RSRC_FREE},
    {"RSRC_GADDR",         TOK_RSRC_GADDR},
    {"RSRC_LOAD",          TOK_RSRC_LOAD},
    {"RSRC_OBFIX",         TOK_RSRC_OBFIX},
    {"RSRC_SADDR",         TOK_RSRC_SADDR},
    {"RUN",                TOK_RUN},
    {"SAVE",               TOK_SAVE},
    {"SCRP_READ",          TOK_SCRP_READ},
    {"SCRP_WRITE",         TOK_SCRP_WRITE},
    {"SDPOKE",             TOK_SDPOKE},
    {"SEEK",               TOK_SEEK},
    {"SELECT",             TOK_SELECT},
    {"SETCOLOR",           TOK_SETCOLOR},
    {"SETDRAW",            TOK_SETDRAW},
    {"SETMOUSE",           TOK_SETMOUSE},
    {"SETTIME",            TOK_SETTIME},
    {"SGET",               TOK_SGET},
    {"SGN",                TOK_SGN},
    {"SHEL_ENVRN",         TOK_SHEL_ENVRN},
    {"SHEL_FIND",          TOK_SHEL_FIND},
    {"SHEL_GET",           TOK_SHEL_GET},
    {"SHEL_PUT",           TOK_SHEL_PUT},
    {"SHEL_READ",          TOK_SHEL_READ},
    {"SHEL_WRITE",         TOK_SHEL_WRITE},
    {"SHL",                TOK_SHL},
    {"SHOWM",              TOK_SHOWM},
    {"SHR",                TOK_SHR},
    {"SIN",                TOK_SIN},
    {"SINGLE",             TOK_SINGLE},
    {"SINH",               TOK_SINH},
    {"SINQ",               TOK_SINQ},
    {"SLPOKE",             TOK_SLPOKE},
    {"SOUND",              TOK_SOUND},
    {"SPACE",              TOK_SPACE_TOK},
    {"SPACE$",             TOK_SPACE_TOK},
    {"SPC",                TOK_SPC},
    {"SPOKE",              TOK_SPOKE},
    {"SPRITE",             TOK_SPRITE},
    {"SPUT",               TOK_SPUT},
    {"SQR",                TOK_SQR},
    {"SSORT",              TOK_SSORT},
    {"STE?",               TOK_STE},
    {"STEP",               TOK_STEP},
    {"STICK",              TOK_STICK},
    {"STOP",               TOK_STOP},
    {"STORE",              TOK_STORE},
    {"STR",                TOK_STR_TOK},
    {"STR$",               TOK_STR_TOK},
    {"STRIG",              TOK_STRIG},
    {"STRING",             TOK_STRING_TOK},
    {"STRING$",            TOK_STRING_TOK},
    {"SUB",                TOK_SUB_TOK},
    {"SUCC",               TOK_SUCC},
    {"SWAP",               TOK_SWAP},
    {"SYSTEM",             TOK_SYSTEM},
    {"TAB",                TOK_TAB},
    {"TAN",                TOK_TAN},
    {"TANH",               TOK_TANH},
    {"TEXT",               TOK_TEXT},
    {"THEN",               TOK_THEN},
    {"TIME",               TOK_TIME_TOK},
    {"TIME$",              TOK_TIME_TOK},
    {"TIMER",              TOK_TIMER_TOK},
    {"TITLEW",             TOK_TITLEW},
    {"TO",                 TOK_TO},
    {"TOPW",               TOK_TOPW},
    {"TOUCH",              TOK_TOUCH},
    {"TRACE",              TOK_TRACE},
    {"TRACE$",             TOK_TRACE},
    {"TRIM",               TOK_TRIM_TOK},
    {"TRIM$",              TOK_TRIM_TOK},
    {"TROFF",              TOK_TROFF},
    {"TRON",               TOK_TRON},
    {"TRUE",               TOK_TRUE},
    {"TRUNC",              TOK_TRUNC_TOK},
    {"TT?",                TOK_TT},
    {"TYPE",               TOK_TYPE_TOK},
    {"UCASE",              TOK_UCASE},
    {"UCASE$",             TOK_UCASE},
    {"UNTIL",              TOK_UNTIL},
    {"UPPER",              TOK_UPPER_TOK},
    {"UPPER$",             TOK_UPPER_TOK},
    {"USING",              TOK_PRINT_USING},
    {"V:",                 TOK_VARPTR},
    {"VAL",                TOK_VAL},
    {"VAL?",               TOK_VAL_COUNT},
    {"VAR",                TOK_VAR},
    {"VARIAT",             TOK_VARIAT},
    {"VARPTR",             TOK_VARPTR},
    {"VDIBASE",            TOK_CONTRL},
    {"VDISYS",             TOK_VDISYS},
    {"VOID",               TOK_VOID},
    {"VQT_EXTENT",         TOK_VQT_EXTENT},
    {"VQT_NAME",           TOK_VQT_NAME},
    {"VSETCOLOR",          TOK_VSETCOLOR},
    {"VST_LOAD_FONTS",     TOK_VST_LOAD_FONTS},
    {"VST_UNLOAD_FONTS",   TOK_VST_UNLOAD_FONTS},
    {"VSYNC",              TOK_VSYNC},
    {"VTAB",               TOK_VTAB},
    {"V_CLRWK",            TOK_V_CLRWK},
    {"V_CLSVWK",           TOK_V_CLSVWK},
    {"V_CLSWK",            TOK_V_CLSWK},
    {"V_OPNVWK",           TOK_V_OPNVWK},
    {"V_OPNWK",            TOK_V_OPNWK},
    {"V_UPDWK",            TOK_V_UPDWK},
    {"W:",                 TOK_W_COLON},
    {"WAVE",               TOK_WAVE},
    {"WEND",               TOK_WEND},
    {"WHILE",              TOK_WHILE},
    {"WINDOW",             TOK_WINDOW},
    {"WINDTAB",            TOK_WINDTAB},
    {"WIND_CALC",          TOK_WIND_CALC},
    {"WIND_CLOSE",         TOK_WIND_CLOSE},
    {"WIND_CREATE",        TOK_WIND_CREATE},
    {"WIND_DELETE",        TOK_WIND_DELETE},
    {"WIND_FIND",          TOK_WIND_FIND},
    {"WIND_GET",           TOK_WIND_GET},
    {"WIND_OPEN",          TOK_WIND_OPEN},
    {"WIND_SET",           TOK_WIND_SET},
    {"WIND_UPDATE",        TOK_WIND_UPDATE},
    {"WORD",               TOK_WORD_TOK},
    {"WORK_OUT",           TOK_WORK_OUT},
    {"WRITE",              TOK_PRINT},
    {"W_HAND",             TOK_W_HAND},
    {"W_INDEX",            TOK_W_INDEX},
    {"XBIOS",              TOK_XBIOS},
    {"XOR",                TOK_XOR_OP},
    {"_C",                 TOK__C},
    {"_DATA",              TOK__DATA},
    {"_X",                 TOK__X},
    {"_Y",                 TOK__Y},
};

const int gfa_keyword_count = (int)(sizeof(gfa_keywords) /
                                     sizeof(gfa_keywords[0]));

/*
 * Comparateur pour strcasecmp portable C89.
 */
static int cmp_ignore_case(const char *a, const char *b)
{
    while (*a != '\0' && *b != '\0') {
        int ca, cb;
        ca = toupper((unsigned char)*a);
        cb = toupper((unsigned char)*b);
        if (ca != cb) return ca - cb;
        a++; b++;
    }
    return (unsigned char)*a - (unsigned char)*b;
}

/*
 * Recherche dichotomique dans la table triee des mots-cles.
 */
gfa_token_type gfa_keyword_lookup(const char *name)
{
    int low, high, mid, cmp;

    if (name == NULL || name[0] == '\0') return TOK_IDENTIFIER;

    low  = 0;
    high = gfa_keyword_count - 1;

    while (low <= high) {
        mid = (low + high) / 2;
        cmp = cmp_ignore_case(name, gfa_keywords[mid].name);

        if (cmp == 0) {
            return gfa_keywords[mid].token;
        } else if (cmp < 0) {
            high = mid - 1;
        } else {
            low = mid + 1;
        }
    }

    return TOK_IDENTIFIER;
}

const char *gfa_keyword_get_name(gfa_token_type type)
{
    /* Search the keyword table for matching token type */
    int i;
    for (i = 0; i < gfa_keyword_count; i++) {
        if (gfa_keywords[i].token == type)
            return gfa_keywords[i].name;
    }
    /* Fallback: use the old names array (may be wrong) */
    if (type >= 0) {
        /* Use the static names table */
        static const char *fallback_names[] = {
            "EOF","EOL","IF","THEN","ELSE","ENDIF","FOR","TO","STEP","NEXT",
            "DOWNTO","WHILE","WEND","REPEAT","UNTIL","DO","LOOP","EXIT_IF",
            "GOTO","GOSUB","RETURN","ON","ON_ERROR","ON_BREAK","ON_MENU",
            "SELECT","CASE","DEFAULT","ENDSELECT","STOP","END","CONT","QUIT",
            "LET","DIM","ERASE","CLEAR","CLR","OPTION_BASE","PROCEDURE",
            "FUNCTION","ENDFUNC","LOCAL","VAR","DEFFN","FN",
            "DEFBIT","DEFBYT","DEFWRD","DEFNUM","DEFFLT","DEFSTR","DEFDBL",
            "DEFLIST","DEFMARK","DEFLINE","DEFTEXT","DEFMOUSE","DEFFILL",
            "DATA","READ","RESTORE","_DATA","PRINT","PRINT_AT","PRINT_USING",
            "INPUT","LINE_INPUT","INKEY","INP","OUT","CLS","LOCATE",
            "POS","CRSCOL","CRSLIN","HTAB","VTAB","TAB","SPC","CLIP","ACLIP",
            "OPEN","CLOSE","OPENW","CLOSEW",
            "SEEK","RELSEEK","EOF","LOF","LOC",
            "BLOAD","BSAVE","BGET","BPUT","SGET","SPUT","FIELD","LSET","RSET",
            "EXIST","KILL","NAME","FILES","DIR","MKDIR","RMDIR","CHDIR","CHDRIVE",
            "FSFIRST","FSNEXT","FSETDTA","FGETDTA",
            "SAVE","LOAD","MERGE","LIST","LLIST","NEW","RUN","CHAIN",
            "DELETE","RENUM","AUTO","PSAVE","STORE","RECALL",
            "COLOR","SETCOLOR","VSETCOLOR",
            "LINE","ALINE","HLINE","BOX","RBOX","PBOX","PRBOX","ARECT",
            "CIRCLE","PCIRCLE","PELLIPSE",
            "POLYLINE","POLYFILL","POLYMARK","APOLY","FILL","BOUNDARY",
            "PLOT","POINT","PTST","CURVE","ATEXT","ACHAR","TEXT","BITBLT",
            "GET","PUT","MODE","HARDCOPY","SETDRAW","DRAW",
            "TITLEW","INFOW","TOPW","GETSIZE","WINDTAB",
            "WIND_OPEN","WIND_CLOSE","WIND_DELETE","WIND_FIND",
            "WIND_CREATE","WIND_CALC","WIND_GET","WIND_SET","WIND_UPDATE",
            "W_HAND","W_INDEX","MW_OUT","SHOWM","HIDEM",
            "ALERT","FILESELECT","FSEL_INPUT",
            "APPL_INIT","APPL_EXIT","APPL_FIND",
            "APPL_READ","APPL_WRITE","APPL_TPLAY","APPL_TRECORD",
            "FORM_ALERT","FORM_BUTTON","FORM_CENTER","FORM_DIAL",
            "FORM_DO","FORM_ERROR","FORM_KEYBD","FORM_INPUT","FORM_INPUT_AS",
            "MENU_BAR","MENU_ICHECK","MENU_IENABLE","MENU_REGISTER",
            "MENU_TEXT","MENU_TNORMAL","MENU","MENU_KILL","MENU_OFF",
            "ON_MENU_GOSUB","ON_MENU_BUTTON","ON_MENU_KEY",
            "ON_MENU_IBOX","ON_MENU_MESSAGE","ON_MENU_OBOX",
            "OB_ADR","OB_FLAGS","OB_H","OB_HEAD","OB_NEXT",
            "OB_SPEC","OB_STATE","OB_TAIL","OB_TYPE","OB_X","OB_Y","OB_W",
            "OBJC_ADD","OBJC_CHANGE","OBJC_DELETE","OBJC_DRAW",
            "OBJC_EDIT","OBJC_FIND","OBJC_OFFSET","OBJC_ORDER",
            "RSRC_LOAD","RSRC_FREE","RSRC_GADDR","RSRC_SADDR","RSRC_OBFIX",
            "GRAF_DRAGBOX","RC_COPY","RC_INTERSECT","RCALL",
            "SCRP_READ","SCRP_WRITE",
            "SHEL_READ","SHEL_WRITE","SHEL_GET","SHEL_PUT",
            "SHEL_FIND","SHEL_ENVRN","EXEC","SYSTEM",
            "GEMDOS","BIOS","XBIOS","GEMSYS","VDISYS",
            "CONTRL","INTIN","INTOUT","PTSIN","PTSOUT",
            "GINTIN","GINTOUT","WORK_OUT",
            "V_OPNWK","V_CLSWK","V_OPNVWK","V_CLSVWK",
            "V_CLRWK","V_UPDWK",
            "VQT_EXTENT","VQT_NAME","VST_LOAD_FONTS","VST_UNLOAD_FONTS","VSYNC",
            "SOUND","BEEP","WAVE","DMACONTROL","DMASOUND",
            "EVERY","AFTER",
            "EVNT_MULTI","EVNT_MESAG","EVNT_KEYBD","EVNT_MOUSE",
            "EVNT_BUTTON","EVNT_TIMER","EVNT_DCLICK",
            "MOUSE","MOUSEX","MOUSEY","MOUSEK","SETMOUSE",
            "STICK","STRIG","PADX","PADY","PADT","LPENX","LPENY","TOUCH",
            "PEEK","POKE","DPEEK","DPOKE","LPEEK","LPOKE",
            "SPOKE","SDPOKE","SLPOKE",
            "BMOVE","MALLOC","MFREE","FRE","MSHRINK",
            "HIMEM","HIDEM","RESERVE","BASEPAGE","ABSOLUTE","ARRPTR","VARPTR",
            "BTST","BSET","BCLR","BCHG","SHL","SHR","ROL","ROR",
            "MAT","MAT_READ","MAT_INPUT","MAT_PRINT",
            "MAT_SET","MAT_CLR","MAT_ONE",
            "MAT_CPY","MAT_XCPY","MAT_TRANS",
            "MAT_ADD","MAT_SUB","MAT_MUL",
            "MAT_DET","MAT_QDET","MAT_RANG","MAT_INV","MAT_NORM",
            "MAT_BASE","MAT_ABS","MAT_NEG",
            "ARRAYFILL","INSERT","SWAP","QSORT","SSORT",
            "TIME$","TIMER","DATE$","SETTIME","DELAY","PAUSE",
            "TRON","TROFF","TRACE$","MONITOR",
            "REM","VOID","~","SPRITE","DUMP",
            "TRUE","FALSE","PI","_C","_X","_Y",
            "C:","CALL","INLINE","RANDOMIZE","RANDOM",
            "ERROR","FATAL","ERR","RESUME",
            "ADD","SUB","MUL","DIV",
            "STE?","TT?",
            "ABS","ASC","ATN","ASIN","ACOS",
            "SIN","COS","TAN","SINH","COSH","TANH","SINQ","COSQ",
            "EXP","LOG","LOG10","SQR",
            "INT","FRAC","FIX","ROUND","CEIL","TRUNC",
            "SGN","DEG","RAD",
            "MIN","MAX","EVEN","ODD","PRED","SUCC",
            "FACT","COMBIN","VARIAT","RND","CFLOAT","CINT",
            "LEN","MID$","LEFT$","RIGHT$",
            "INSTR","RINSTR","STR$","VAL","VAL?",
            "CHR$","BIN$","HEX$","OCT$",
            "UPPER$","LCASE$","LOWER$",
            "TRIM$","STRING$","SPACE$",
            "MKI$","MKL$","MKS$","MKF$","MKD$",
            "CVI","CVL","CVS","CVF","CVD",
            "BYTE","CARD","WORD","LONG","SINGLE","DOUBLE",
            "LPOS","STICK()","STRIG()","PAD()","TOUCH()",
            "KEYDEF","KEYGET","KEYLOOK","KEYPAD","KEYPRESS","KEYTEST",
            "INPUT$","INPMID$","DIR$","DIM?","DFREE","TYPE",
            "+","-","*","/","^",
            "=","<",">","<=",">=","<>",
            "AND","OR","XOR","NOT","EQV","IMP","MOD","DIV",
            "&","==","@",
            "(",")",",",";",":","#","'","!",
            "INTEGER","FLOAT","STRING","IDENTIFIER","LABEL",
            "W:","L:"
        };
        int fallback_count = (int)(sizeof(fallback_names)/sizeof(fallback_names[0]));
        if ((int)type < fallback_count)
            return fallback_names[(int)type];
    }
    return "UNKNOWN";
}
